name: Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  issues:
    name: Issue Workflow
    runs-on: ubuntu-latest
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"          
          echo "Issue body: ${{ github.event.issue.body }}"
